### ISSUE TITLE
Big file selection issue

### ISSUE THREAD

**Issue by otaryan93** [cyph/cordova-plugin-chooser#1]
When I select big file it just bring message that "App closed" and close the application.
I was expecting that I will get at least an error message in catch.

**Comment by buu700** [comment]
Thanks for the report! I meant to add a note to the readme the other day and forgot, but this can be fixed on Android by adding the following to config.xml:

```
<edit-config
	file="app/src/main/AndroidManifest.xml"
	mode="merge"
	target="/manifest/application"
>
	<application android:largeHeap="true" />
</edit-config>
```

**Comment by otaryan93** [comment]
Thank you for fast response.
Do we have the same issue in iOS?
I just was not able to check it in iOS

**Comment by buu700** [comment]
Not 100% sure; I'll have to test that out in the near future and get back to you.

(I did actually quickly test this a week or so ago and it hanged without anything appearing to crash, so it at least doesn't have the exact same issue; but the only iOS device I have on hand right now is an old iPod Touch that's super slow in general, so it could just be that I didn't wait long enough.)

**Comment by zubinraja** [comment]
Have already mentioned android:largeHeap="true" for large files.
But app crashes while selecting file with size above 100MB

**Comment by spinybeast** [comment]
@zubinraja Hi! Did you solve this? I have same problem

**Comment by zubinraja** [comment]
@spinybeast I used different plugin to solve this. used cordova-plugin-filechooser for android and cordova-plugin-filepicker for iOS
