### ISSUE TITLE
Error Ios

### ISSUE THREAD

**Issue by Juanperezc** [cyph/cordova-plugin-chooser#10]
I have the next error when I try test the plugin in my device (iphone 6)

`Error: Uncaught (in promise): Error: Token must be defined!`

**Comment by buu700** [comment]
Hm, are you sure that's related to this plugin? I see that that error message is related to Angular dependency injection but can't find any incidence of it in relation to the iOS DocumentPicker API that this depends on.

If you're using Ionic, it's possible that you just didn't import the module correctly.

**Comment by Juanperezc** [comment]
I just downgrade to version 4.9.0, this solve the problem
