### ISSUE TITLE
Build fails after adding android:largeHeap="true"

### ISSUE THREAD

**Issue by akadebnath** [cyph/cordova-plugin-chooser#19]
After I added below code block, build fails

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
	<application android:largeHeap="false" />
</edit-config>
```
Below is the error message:

![image](https://user-images.githubusercontent.com/18642790/66976872-1f89f500-f0c1-11e9-9922-92edec941616.png)

**Comment by joshuakaleb0424** [comment]
I know this question is quite old.  Found the answer here. https://github.com/dpa99c/cordova-custom-config/issues/24#issuecomment-172981002

tldr; add xmlns:android="http://schemas.android.com/apk/res/android to the widget tag.

**Comment by Ferdzzzzzzzz** [comment]
Much appreciated @joshuakaleb0424
