### ISSUE TITLE
AAPT2 error on Android

### ISSUE THREAD

**Issue by rricamar** [cyph/cordova-plugin-chooser#2]
Hi,

Today I was using your plugin, after set the 

```xml
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
  <application android:largeHeap="true" />
</edit-config>
```

on my `config.xml` , I faced this error:

```java
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
```

While trying to do a `ionic cordova build android`. If I remove that, the build is successful as always.

Info: `<engine name="android" spec="~7.0.0" />`

Thank you in advance.

**Comment by danilopolani** [comment]
@rricamar how did you fix this? +1 for me with Ionic 3.

**Comment by rricamar** [comment]
Hi @danilopolani , finally I use the Cordova Camera Plugin ( https://ionicframework.com/docs/v3/native/camera/ , https://github.com/apache/cordova-plugin-camera#cameramediatype--enum ) which allows select files from any type with the `ALLMEDIA` config 👍

**Comment by danilopolani** [comment]
Oh well, thank you!
