### ISSUE TITLE
Catch returns success and then() returns error

### ISSUE THREAD

**Issue by sinan92** [cyph/cordova-plugin-chooser#22]
Is it just me or is this how this package works? This is how I am using this plugin:

            this.fileChooser.getFile().then((error) => {
                console.log(error); // Error??
            }).catch((file) => {
                this.uploadFile(file.uri); // Success
            });

**Comment by buu700** [comment]
Uh, no, that's definitely not right :/. Are you using the Ionic service?

**Comment by sinan92** [comment]
Yes I am

**Comment by buu700** [comment]
Got it, thanks for clarifying that! Looks like this actually is a bug in the Ionic integration, but I can put a quick fix in here.

**Comment by sinan92** [comment]
Alright, thanks! :)
