### ISSUE TITLE
Android does not accept mime type

### ISSUE THREAD

**Issue by sinan92** [cyph/cordova-plugin-chooser#23]
_I didn't want to ask this in the previous ticket because it's a different question but..._

I noticed that iOS picks up on the mime type perfectly (tested with "text/csv" and"application/vnd.ms-excel") but for some reason Android does not. It just greys out everything.

Is this also related to Ionic or is it a known issue?

Although those don't work, this one does work for android: "text/*". I encountered the same problem in the file-chooser plugin.

**Comment by buu700** [comment]
Hm, that sounds like a separate issue, although it's worth trying again with the latest version to see if it's still reproducible.

**Comment by sinan92** [comment]
My bad, apparently Android reads is as "text/comma-separated-values" while iOS sees it as "text/csv". I hope this might help someone else.

**Comment by buu700** [comment]
Ahh, that's a pain. I'll make a note that I should look into a solution for standardizing the mime types between Android and iOS at some point, or if this is a lone edge case to just have a special case conversion between the two depending on the platform.

**Comment by arunavsikdershuvo** [comment]
> My bad, apparently Android reads is as "text/comma-separated-values" while iOS sees it as "text/csv". I hope this might help someone else.

@sinan92 Thank you for saving my time.
