### ISSUE TITLE
Possibility to exclude the data and dataUri from the response when getting a file. 

### ISSUE THREAD

**Issue by tijlreynhout** [cyph/cordova-plugin-chooser#26]
Currently the repsonse when getting a file includes the data as a byte array and the dataUri. This causes the selection of big files to become demanding of the phone. While for some usages they are not needed. In my case I show a preview of the video/image and then a user can upload it to the server. I do not need the dateUri for that but my phone starts to lag because it is always included, this can also cause crashes for very big files.

**Comment by buu700** [comment]
Great idea! There's a new `getFileMetadata` method you can use for that now.

**Comment by tijlreynhout** [comment]
Wow great this functionality was implemented so fast! Great plugin btw! I have but one more question.. Will this be accessible through the ionic native plugin? Or do you have no control over that?
