### ISSUE TITLE
Android - Open from Drive - Only directories

### ISSUE THREAD

**Issue by thalassa-web** [cyph/cordova-plugin-chooser#9]
On Android, when I try to choose a file from Google Drive, I see directories present in my drive but when I click on one of the directory, I see the message «Aucun élément» (That means «No element» in French).
It worked before, but it's maybe an bug since a new version of Google Drive application ?

**Comment by tii-bruno** [comment]
So I made some tests by making changes in Chooser.java.
If I comment the line «intent.putExtra(Intent.EXTRA_MIME_TYPES, accept.split(","));» I have no problems (on the exception if I would like filtering by mime type …)

**Comment by buu700** [comment]
Hmm, yeah, this definitely used to work, but I just tested and I'm seeing the same behavior as you. Thanks for looking into the root cause and fix for me!
